#  
# Copyright (C) 2016-2022 phantombot.github.io/PhantomBot
#  
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#  
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

version: '3'
services:
  phantombot:
    container_name: phantombot
    image: ghcr.io/phantombot/phantombot
    ports:
      - "25000:25000"
    restart: always
    volumes:
      - PhantomBot_data:/opt/PhantomBot_data
    environment:
      # ------ Set any botlogin.txt variable here, with the PHANTOMBOT_ prefix.
      # ------ Note that after first run, botlogin.txt takes priority.
      # Twitch bot user (Required)
      PHANTOMBOT_USER: ""
      # Twitch bot user OAuth token (https://phantombot.github.io/PhantomBot/oauth/) (Required)
      PHANTOMBOT_OAUTH: "nothing"
      # Twitch caster channel (Required)
      PHANTOMBOT_CHANNEL: ""
      # Webinterface username
      PHANTOMBOT_PANELUSER: ""
      # Webinterface password
      PHANTOMBOT_PANELPASSWORD: ""
      # Webinterface use https?
      PHANTOMBOT_USEHTTPS: "true"
      # Enables the restart button in the panel
      PHANTOMBOT_RESTARTCMD: "/opt/PhantomBot/restartbot-docker.sh"

volumes:
  PhantomBot_data:
