#  
# Copyright (C) 2016-2020 phantom.bot
#  
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#  
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

version: '3'
services:

  caddy:
    container_name: caddy
    image: caddy:latest
    ports:
      - 443:443
    restart: always
    depends_on:
      - phantombot
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    command: [
      "caddy",
      "reverse-proxy",
      "--from",
      "${DOMAIN:-localhost}",
      "--to",
      "phantombot-nightly:25000"
    ]

  phantombot:
    # build: 
    #   context: .
    #   dockerfile: Dockerfile
    #   args:
    #     PROJECT_VERSION: $PROJECT_VERSION
    #     TARGETPLATFORM: ${TARGETPLATFORM:-linux/amd64}
    container_name: phantombot-nightly
    image: gmt2001/phantombot-nightly:latest
    restart: always
    volumes:
      - PhantomBot_data:/opt/PhantomBot_data
    environment:
      # ------ Override any botlogin.txt variable here, with the PHANTOMBOT_ prefix
      # Twitch bot user (Required)
      PHANTOMBOT_USER:
      # Twitch bot user OAuth token (https://twitchapps.com/tmi/) (Required)
      PHANTOMBOT_OAUTH:
      # Twitch caster channel OAuth token (https://phantom.bot/oauth/)
      PHANTOMBOT_APIOAUTH:
      # Twitch caster channel (Required)
      PHANTOMBOT_CHANNEL:
      # Webinterface username
      PHANTOMBOT_PANELUSER:
      # Webinterface password
      PHANTOMBOT_PANELPASSWORD:

volumes:
  caddy_data:
  caddy_config:
  PhantomBot_data:
