name: Java CI
on:
  push:
    branches:
      - '*'
      - '!edge'
  pull_request:
    branches:
      - '*'
jobs:
  buildtest:
    name: Test Build on ubuntu-latest with JDK 11.0.11
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Set up JDK 11.0.11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 11.0.11
    - name: Set up Ant
      run: sudo apt-get install ant
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml test
