name: Build JLink Binaries

on:
  workflow_dispatch:

jobs:
  updatejlink:
    name: Update JLink Builds
    strategy:
      matrix:
        include:
          - osname: Linux (GCC, x86_64)
            java-version: 17
            java-distribution: 'temurin'
            folder: java-runtime-linux
            qemu: false
            os: ubuntu-latest
            script: jlink-jdk-linux.sh
          - osname: Linux (GCC, arm64)
            java-version: 17
            java-distribution: 'temurin'
            folder: java-runtime-arm64
            qemu: true
            platform: linux/arm64
            image: eclipse-temurin:17-jdk
            os: ubuntu-latest
            script: jlink-jdk-docker.sh
            jdk: /opt/java/openjdk
          - osname: Linux (GCC, arm32)
            java-version: 17
            java-distribution: 'temurin'
            folder: java-runtime-arm32
            qemu: true
            platform: linux/arm/v7
            image: eclipse-temurin:17-jdk
            os: ubuntu-latest
            script: jlink-jdk-docker.sh
            jdk: /opt/java/openjdk
          - osname: Windows
            java-version: 17
            os: windows-latest
            java-distribution: 'temurin'
            folder: java-runtime
            qemu: false
            script: jlink-jdk.bat
          - osname: macOS
            java-version: 17
            java-distribution: 'temurin'
            folder: java-runtime-macos
            qemu: false
            os: macos-latest
            script: jlink-jdk-macos.sh
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Set up QEMU
      if: matrix.qemu == true
      uses: docker/setup-qemu-action@v3
      with:
        platforms: ${{ matrix.platform }}
    - name: Set up JDK
      if: matrix.qemu == false
      id: setup-java
      uses: actions/setup-java@v4
      with:
        distribution: ${{ matrix.java-distribution }}
        java-version: ${{ matrix.java-version }}
        check-latest: true
    - name: Run JLink (Windows)
      if: matrix.os == 'windows-latest'
      env:
        FOLDER: ${{ matrix.folder }}
        SCRIPT: ${{ matrix.script }}
        JDK: ${{ steps.setup-java.outputs.path }}
      run: |
        cd development-resources
        cmd /C $env:SCRIPT
    - name: Run JLink (Non-Windows)
      if: matrix.os != 'windows-latest' && !matrix.qemu
      env:
        FOLDER: ${{ matrix.folder }}
        SCRIPT: ${{ matrix.script }}
        JDK: ${{ steps.setup-java.outputs.path }}
      run: |
        cd development-resources
        chmod +x $SCRIPT
        /bin/bash $SCRIPT
    - name: Run JLink (Docker)
      if: matrix.qemu == true
      env:
        FOLDER: ${{ matrix.folder }}
        SCRIPT: ${{ matrix.script }}
        JDK: ${{ matrix.jdk }}
        PLATFORM: ${{ matrix.platform }}
        IMAGE: ${{ matrix.image }}
      run: |
        cd development-resources
        chmod +x $SCRIPT
        /bin/bash $SCRIPT
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.folder }}
        path: resources/${{ matrix.folder }}/**
        if-no-files-found: error
        retention-days: 1
  commit:
    name: Commit Binaries
    runs-on: ubuntu-latest
    needs: updatejlink
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_TOKEN }}
    - name: Download Artifacts
      uses: actions/download-artifact@v5
      with:
        path: resources
    - name: Commit Changes
      uses: EndBug/add-and-commit@v9
      with:
        message: Updated the Java binaries
        default_author: github_actions